[project]
name = "bliss-attractors"
version = "0.1.0"
description = "🌀"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Tomek Korbak", email = "tomasz.korbak@gmail.com" }
]
dependencies = [
    "accelerate>=1.8.1",
    "anthropic>=0.52.2",
    "inspect-ai>=0.3.100",
    "openai>=1.84.0",
    "torch>=2.7.1",
    "transformers>=4.53.1",
]

[project.entry-points.inspect_ai]
bliss_attractors = "tasks.py"

[tool.ruff]
line-length = 120
target-version = "py312"
select = ["E", "F", "I", "B", "W"]
